default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mecab_heroku_example_app_development

test:
  <<: *default
  database: mecab_heroku_example_app_test

production:
  <<: *default
  database: mecab_heroku_example_app_production
  username: mecab_heroku_example_app
  password: <%= ENV['MECAB_HEROKU_EXAMPLE_APP_DATABASE_PASSWORD'] %>
